name: Publish

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v4.1.1

    - uses: actions/setup-node@v4.0.1
      with:
        node-version: 18.x

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.CLIENT_ID }}
        tenant-id: ${{ secrets.TENANT_ID }}
        subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

    - name: Build
      run: |
        npm ci
        npm run build

    - name: Deploy Azure
      uses: azure/CLI@v1
      with:
        azcliversion: 2.47.0
        inlineScript: |
          az bicep install

          OUTPUT=$(az deployment group create \
            --resource-group recipes \
            --name recipes-deploy \
            --template-file deploy/main.bicep \
            --parameters \
                domainName=ant.ninja \
                subDomainName=recipes \
                dnsResourceGroup=dns \
            --query "[properties.outputs.stgAccName.value]" \
            --output tsv)
          
          STG_ACC_NAME=$(awk 'NR == 1' <<<$OUTPUT)

          az storage blob service-properties update \
            --account-name $STG_ACC_NAME \
            --static-website \
            --404-document 404.html \
            --index-document index.html
          
          az storage blob sync \
            --account-name $STG_ACC_NAME \
            --source public \
            --container "\$web"