name: Publish

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v4.2.1

    - uses: actions/setup-node@v4.0.4
      with:
        node-version: 18.x

    - name: Install
      run: npm ci

    - name: Build
      run: npm run build

    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy Infra
      id: deploy
      uses: azure/deploy@main
      with:
        type: deploymentStack
        operation: create
        name: recipes
        scope: resourceGroup
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resource-group-name: recipes
        parameters-file: deploy/main.bicepparam
        action-on-unmanage-resources: delete
        deny-settings-mode: denyWriteAndDelete
        deny-settings-excluded-actions: |
          Microsoft.Storage/storageAccounts/listKeys/action,
          Microsoft.ManagedIdentity/userAssignedIdentities/assign/action
    
    - name: Upload Site
      uses: azure/CLI@v2
      with:
        azcliversion: latest
        inlineScript: |
          az storage blob service-properties update \
            --account-name ${{steps.deploy.outputs.stgAccName}} \
            --static-website \
            --404-document 404.html \
            --index-document index.html
          
          az storage blob sync \
            --account-name ${{steps.deploy.outputs.stgAccName}} \
            --source public \
            --container "\$web"