name: Publish

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v3.2.0

    - uses: actions/setup-node@v3.5.1
      with:
        node-version: 14.x

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.CLIENT_ID }}
        tenant-id: ${{ secrets.TENANT_ID }}
        subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

    - name: Build
      run: |
        npm ci
        npm run build

    - name: Deploy Azure
      uses: azure/CLI@v1
      with:
        inlineScript: |
          OUTPUT=$(az deployment group create \
            --resource-group recipes \
            --name recipes-deploy \
            --template-file deploy/main.bicep \
            --query "[properties.outputs.stgAccName.value, properties.outputs.stgAccKey.value]" \
            --output tsv)
          
          STG_ACC_NAME=$(awk 'NR == 1' <<<$OUTPUT)
          STG_ACC_KEY=$(awk 'NR == 2' <<<$OUTPUT)

          az storage blob service-properties update \
            --account-name $STG_ACC_NAME \
            --static-website \
            --404-document 404.html \
            --index-document index.html
          
          az storage blob sync \
            --account-name $STG_ACC_NAME \
            --account-key $STG_ACC_KEY \
            --source public \
            --container "\$web"